CREATE SCHEMA IF NOT EXISTS `tbl` DEFAULT CHARACTER SET utf8mb4;
USE `tbl`;

-- Table for ROW_ID
CREATE TABLE ROW_NAME (
	ROW_ID VARCHAR(10) PRIMARY KEY UNIQUE
);

-- Table for stock
CREATE TABLE STOCK (
    ID INT AUTO_INCREMENT PRIMARY KEY, 
    ROW_ID VARCHAR(10) NOT NULL,
    PALLATE INT NOT NULL,
    UPDATE_DATE DATE NOT NULL,
    FOREIGN KEY (ROW_ID) REFERENCES ROW_NAME(ROW_ID)
);

-- Table for row pallet
CREATE TABLE ROW_PALLATE (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    ROW_ID VARCHAR(10) NOT NULL,
    PALLATE_NO INT NOT NULL,
    EACH_PALLATE INT NOT NULL,
    UPDATE_DATE DATE NOT NULL,
    FOREIGN KEY (ROW_ID) REFERENCES ROW_NAME(ROW_ID)
);

-- Table for row each pallet
CREATE TABLE ROW_EACH_PALLATE (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    ROW_ID VARCHAR(10) NOT NULL,
    PALLATE_NO INT NOT NULL,
    DISTANCE DECIMAL(5,2) NOT NULL,
    ANGLE_X DECIMAL(5,2) NOT NULL,
    ANGLE_Y DECIMAL(5,2) NOT NULL,
    UPDATE_DATE DATE NOT NULL,
    FOREIGN KEY (ROW_ID) REFERENCES ROW_NAME(ROW_ID)
);