CREATE SCHEMA IF NOT EXISTS `datasensor` DEFAULT CHARACTER SET utf8mb4;
USE `datasensor`;

-- Table for location
CREATE TABLE LOCATION (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    ROW_ID CHAR(10) UNIQUE NOT NULL,
    AREA INT NOT NULL,
    NumberOfPages INT NOT NULL
);

-- Insert values into LOCATION table
INSERT INTO LOCATION (ROW_ID, AREA, NumberOfPages) VALUES
('1AA001A', 10, 3), ('1AA002A', 10, 2), ('1AA003A', 10, 2), ('1AA004A', 10, 2), ('1AA005A', 10, 2),
('1AA006A', 10, 2), ('1AA007A', 10, 2), ('1AA008A', 10, 2), ('1AA009A', 10, 2), ('1AA010A', 10, 2),
('1AA011A', 10, 2), ('1AA012A', 10, 2), ('1AA013A', 10, 2), ('1AA014A', 10, 3), ('1AA015A', 5, 2),
('1AA016A', 5, 2), ('1AA017A', 5, 2), ('1AA018A', 5, 2), ('1AA019A', 5, 2), ('1AA020A', 5, 2),
('1AA021A', 5, 2), ('1AA022A', 5, 2), ('1AA023A', 3, 2), ('1AA024A', 3, 2),
('1AA025A', 3, 2), ('1AA026A', 3, 2), ('1AA027A', 3, 2), ('1AA028A', 3, 4);

-- Table for stock
CREATE TABLE STOCK (
    ID INT AUTO_INCREMENT PRIMARY KEY, 
    ROW_ID CHAR(10) NOT NULL,
    PALLET INT,
    UPDATE_DATE DATE NOT NULL,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    UNIQUE (ROW_ID, UPDATE_DATE)
);

-- Table for row pallet
CREATE TABLE ROW_PALLET (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    ROW_ID CHAR(10) NOT NULL,
    PALLET_NO INT,
    EACH_PALLET INT,
    UPDATE_DATE DATE NOT NULL,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (ROW_ID, UPDATE_DATE) REFERENCES STOCK (ROW_ID, UPDATE_DATE)
);

-- Table for row each pallet
CREATE TABLE ROW_EACH_PALLET (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    ROW_ID CHAR(10) NOT NULL,
    PALLET_NO INT NOT NULL,
    DISTANCE DECIMAL(5,2) NOT NULL,
    ANGLE_X DECIMAL(5,2) NOT NULL,
    ANGLE_Y DECIMAL(5,2) NOT NULL,
    UPDATE_DATE DATE NOT NULL,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (ROW_ID, UPDATE_DATE) REFERENCES ROW_PALLET (ROW_ID, UPDATE_DATE)
);
